name: dart_multihash
description: A dart-lang implementation of the Multihash protocol.
version: 0.0.1
homepage: https://github.com/dwyl/dart_multihash
repository: https://github.com/dwyl/dart_multihash
issue_tracker: https://github.com/dwyl/dart_multihash/issues

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  buffer: ^1.1.1

dev_dependencies:
  lints: ^2.0.0
  crypto: ^3.0.2
  convert: ^3.1.1
  test: ^1.16.0
  collection: ^1.17.0